package com.example.runtime

import java.util.regex.Pattern

object HtmlSanitizer {

    /**
     * Inspects raw HTML input. If it is wrapped in ```html ... ```, <pre>&lt;!DOCTYPE html&gt;...,
     * contains escaped HTML entities generated by code exporters, document viewers,
     * or markdown viewers, it extracts and unescapes the true executable HTML application.
     */
    fun extractExecutableHtml(input: String): String {
        var trimmed = input.trim()
        if (trimmed.isEmpty()) return input

        // Case 1: Markdown code block (e.g. ```html ... ``` or ``` ... ```)
        if (trimmed.startsWith("```")) {
            val stripped = trimmed.replaceFirst(Regex("^```[a-zA-Z0-9_-]*\\s*"), "")
                .replace(Regex("\\s*```$"), "")
                .trim()
            if (stripped.isNotEmpty()) {
                trimmed = stripped
            }
        }

        // Case 2: Wrapped inside <pre> ... </pre> or <textarea> ... </textarea> or <xmp> ... </xmp>
        val codeTagPattern = Pattern.compile("<(pre|textarea|xmp|code)[^>]*>([\\s\\S]*?)</\\1>", Pattern.CASE_INSENSITIVE)
        val matcher = codeTagPattern.matcher(trimmed)
        while (matcher.find()) {
            val candidate = matcher.group(2) ?: continue
            val candidateTrimmed = candidate.trim()
            val unescaped = unescapeHtmlEntities(candidateTrimmed).trim()
            if (isExecutableHtmlDoc(unescaped)) {
                return unescaped
            }
            if (isExecutableHtmlDoc(candidateTrimmed)) {
                return candidateTrimmed
            }
        }

        // Case 3: String itself begins with or is predominantly escaped &lt;!DOCTYPE or &lt;html
        if (trimmed.startsWith("&lt;!DOCTYPE", ignoreCase = true) ||
            trimmed.startsWith("&lt;html", ignoreCase = true) ||
            (trimmed.contains("&lt;!DOCTYPE html", ignoreCase = true) && !trimmed.contains("<!DOCTYPE html", ignoreCase = true))) {
            val unescaped = unescapeHtmlEntities(trimmed)
            if (isExecutableHtmlDoc(unescaped)) {
                return unescaped
            }
        }

        // Case 4: Embedded inside arbitrary markdown or document with &lt;!DOCTYPE ... &lt;/html&gt;
        val startIdx = trimmed.indexOf("&lt;!DOCTYPE", ignoreCase = true)
        val endTag = "&lt;/html&gt;"
        val endIdx = trimmed.lastIndexOf(endTag, ignoreCase = true)
        if (startIdx != -1 && endIdx != -1 && endIdx > startIdx) {
            val slice = trimmed.substring(startIdx, endIdx + endTag.length)
            val unescaped = unescapeHtmlEntities(slice)
            if (isExecutableHtmlDoc(unescaped)) {
                return unescaped
            }
        }

        // Case 5: Document starts with <!DOCTYPE or <html
        if (trimmed.startsWith("<!DOCTYPE", ignoreCase = true) || trimmed.startsWith("<html", ignoreCase = true)) {
            // Check if it's an export viewer document whose body only displays another escaped HTML document
            val bodyInnerPattern = Pattern.compile("<body[^>]*>\\s*<(pre|div|code)[^>]*>([\\s\\S]*?)</\\1>\\s*</body>", Pattern.CASE_INSENSITIVE)
            val bodyMatcher = bodyInnerPattern.matcher(trimmed)
            if (bodyMatcher.find()) {
                val innerCode = bodyMatcher.group(2)?.trim() ?: ""
                val unescaped = unescapeHtmlEntities(innerCode)
                if (isExecutableHtmlDoc(unescaped)) {
                    return unescaped
                }
            }
            return trimmed
        }

        // Case 6: Fragment with <body>, <script>, or HTML elements but missing doctype/html wrapper
        if (isExecutableFragment(trimmed)) {
            return """
                <!DOCTYPE html>
                <html>
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                </head>
                <body>
                    $trimmed
                </body>
                </html>
            """.trimIndent()
        }

        return trimmed
    }

    /**
     * Extracts the real application title from <title>AppName</title>, if present.
     */
    fun extractAppTitle(html: String): String? {
        val pattern = Pattern.compile("<title[^>]*>([\\s\\S]*?)</title>", Pattern.CASE_INSENSITIVE)
        val matcher = pattern.matcher(html)
        if (matcher.find()) {
            val title = matcher.group(1)?.trim()
            if (!title.isNullOrBlank() && !title.equals("Doc", ignoreCase = true) && !title.equals("Document", ignoreCase = true) && !title.equals("Untitled", ignoreCase = true)) {
                return title
            }
        }
        return null
    }

    private fun isExecutableHtmlDoc(text: String): Boolean {
        val lower = text.lowercase()
        val hasDocTypeOrHtml = lower.contains("<!doctype html") || lower.contains("<html")
        val hasStructure = lower.contains("<head") || lower.contains("<body") || lower.contains("<script") || lower.contains("</html>") || lower.contains("<div")
        return hasDocTypeOrHtml && hasStructure
    }

    private fun isExecutableFragment(text: String): Boolean {
        val lower = text.lowercase()
        return (lower.contains("<script") || lower.contains("<style") || lower.contains("<div") || lower.contains("<button")) &&
                (lower.contains("</script>") || lower.contains("</style>") || lower.contains("</div>") || lower.contains("</button>"))
    }

    fun unescapeHtmlEntities(text: String): String {
        var t = text
        // Handle double-escaped entities first (e.g. &amp;lt; -> &lt;)
        if (t.contains("&amp;")) {
            t = t.replace("&amp;lt;", "&lt;", ignoreCase = true)
                .replace("&amp;gt;", "&gt;", ignoreCase = true)
                .replace("&amp;amp;", "&amp;", ignoreCase = true)
                .replace("&amp;quot;", "&quot;", ignoreCase = true)
                .replace("&amp;#", "&#", ignoreCase = true)
        }
        return t
            .replace("&lt;", "<", ignoreCase = true)
            .replace("&gt;", ">", ignoreCase = true)
            .replace("&quot;", "\"", ignoreCase = true)
            .replace("&#39;", "'", ignoreCase = true)
            .replace("&apos;", "'", ignoreCase = true)
            .replace("&#x2F;", "/", ignoreCase = true)
            .replace("&#47;", "/", ignoreCase = true)
            .replace("&nbsp;", " ", ignoreCase = true)
            .replace("&amp;", "&", ignoreCase = true)
    }
}
