package com.example.runtime

import java.util.regex.Pattern

object HtmlSanitizer {

    /**
     * Inspects raw HTML input. If it is wrapped in <pre>&lt;!DOCTYPE html&gt;... or
     * contains escaped HTML entities generated by code exporters, document viewers,
     * or markdown viewers, it extracts and unescapes the true executable HTML application.
     */
    fun extractExecutableHtml(input: String): String {
        val trimmed = input.trim()
        if (trimmed.isEmpty()) return input

        // Case 1: Wrapped inside <pre> ... </pre> with escaped HTML entities
        val prePattern = Pattern.compile("<pre[^>]*>([\\s\\S]*?)</pre>", Pattern.CASE_INSENSITIVE)
        val matcher = prePattern.matcher(trimmed)
        while (matcher.find()) {
            val candidate = matcher.group(1) ?: continue
            val unescaped = unescapeHtmlEntities(candidate).trim()
            if (isFullHtmlDoc(unescaped)) {
                return unescaped
            }
        }

        // Case 2: String itself begins with or is predominantly escaped &lt;!DOCTYPE or &lt;html
        if (trimmed.startsWith("&lt;!DOCTYPE", ignoreCase = true) ||
            trimmed.startsWith("&lt;html", ignoreCase = true) ||
            (trimmed.contains("&lt;!DOCTYPE html", ignoreCase = true) && !trimmed.contains("<!DOCTYPE html", ignoreCase = true))) {
            val unescaped = unescapeHtmlEntities(trimmed)
            if (isFullHtmlDoc(unescaped)) {
                return unescaped
            }
        }

        // Case 3: Embedded inside arbitrary markdown or document with &lt;!DOCTYPE ... &lt;/html&gt;
        val startIdx = trimmed.indexOf("&lt;!DOCTYPE", ignoreCase = true)
        val endTag = "&lt;/html&gt;"
        val endIdx = trimmed.lastIndexOf(endTag, ignoreCase = true)
        if (startIdx != -1 && endIdx != -1 && endIdx > startIdx) {
            val slice = trimmed.substring(startIdx, endIdx + endTag.length)
            val unescaped = unescapeHtmlEntities(slice)
            if (isFullHtmlDoc(unescaped)) {
                return unescaped
            }
        }

        // Case 4: Standard HTML document with unescaped tags
        return input
    }

    /**
     * Extracts the real application title from <title>AppName</title>, if present.
     */
    fun extractAppTitle(html: String): String? {
        val pattern = Pattern.compile("<title[^>]*>([\\s\\S]*?)</title>", Pattern.CASE_INSENSITIVE)
        val matcher = pattern.matcher(html)
        if (matcher.find()) {
            val title = matcher.group(1)?.trim()
            if (!title.isNullOrBlank() && !title.equals("Doc", ignoreCase = true) && !title.equals("Document", ignoreCase = true) && !title.equals("Untitled", ignoreCase = true)) {
                return title
            }
        }
        return null
    }

    private fun isFullHtmlDoc(text: String): Boolean {
        val lower = text.lowercase()
        val hasDocTypeOrHtml = lower.contains("<!doctype html") || lower.contains("<html")
        val hasStructure = lower.contains("<head") || lower.contains("<body") || lower.contains("<script") || lower.contains("</html>")
        return hasDocTypeOrHtml && hasStructure
    }

    fun unescapeHtmlEntities(text: String): String {
        return text
            .replace("<br>", "\n", ignoreCase = true)
            .replace("<br/>", "\n", ignoreCase = true)
            .replace("<br />", "\n", ignoreCase = true)
            .replace("&lt;", "<", ignoreCase = true)
            .replace("&gt;", ">", ignoreCase = true)
            .replace("&amp;", "&", ignoreCase = true)
            .replace("&quot;", "\"", ignoreCase = true)
            .replace("&#39;", "'", ignoreCase = true)
            .replace("&apos;", "'", ignoreCase = true)
            .replace("&#x2F;", "/", ignoreCase = true)
            .replace("&#47;", "/", ignoreCase = true)
            .replace("&nbsp;", " ", ignoreCase = true)
    }
}
